AllCops:
  Include:
    - bin/*
    - lib/**/*.rb
    - test/**/*.rb
  Exclude:
    - '[^blt]*/**/*'
  TargetRubyVersion: 2.4


Layout/LineLength:
  Max: 110 # Preferred length is 100
  Exclude:
    - lib/hexapdf/content/canvas.rb
    - lib/hexapdf/serializer.rb
    - test/hexapdf/content/test_parser.rb
    - test/hexapdf/layout/test_text_layouter.rb

Metrics/ParameterLists:
  CountKeywordArgs: false
  Max: 8

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/BlockNesting:
  Max: 5


Style/Encoding:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - test/**/*.rb

Style/StringLiterals:
  Enabled: false # we don't care

Style/RegexpLiteral:
  AllowInnerSlashes: true

Style/NumericLiterals:
  MinDigits: 6

Style/NumericLiteralPrefix:
  EnforcedOctalStyle: zero_only

Style/SymbolArray:
  EnforcedStyle: brackets
  Exclude:
    - lib/hexapdf/type/font_type1.rb

Style/WordArray:
  MinSize: 5

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Lambda:
  EnforcedStyle: lambda

Style/NumericPredicate:
  EnforcedStyle: comparison

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses

Style/FormatString:
  EnforcedStyle: sprintf
  Exclude:
    - lib/hexapdf/cli/command.rb # uses a different format method
    - lib/hexapdf/cli/inspect.rb # uses a different format method

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/YodaCondition:
  EnforcedStyle: forbid_for_equality_operators_only

Style/EmptyElse:
  EnforcedStyle: empty

Style/InverseMethods:
  Exclude:
    - lib/hexapdf/layout/box.rb # false alarm for custom none?

Style/SingleLineMethods:
  Exclude:
    - test/**/*

Style/Documentation:
  Exclude:
    - lib/hexapdf/data_dir.rb # false alaram
    - lib/hexapdf/type/actions.rb # false alaram
    - lib/hexapdf/type/annotations.rb # false alaram
    - lib/hexapdf/layout/text_shaper.rb # false alaram
    - test/**/*

Style/GuardClause:
  Enabled: false # false alarms

Style/Next:
  Enabled: false # not really useful

Style/ParallelAssignment:
  Enabled: false # not really needed

Style/TrivialAccessors:
  Enabled: false

Style/NestedTernaryOperator:
  Enabled: false # compact nested ternary operators are okay

Style/RescueModifier:
  Enabled: false # valid but using it makes life sometimes easier

Style/MutableConstant:
  Enabled: false # valid but sometimes unavoidable

Style/CommentedKeyword:
  Enabled: false # false alarms and we do want yield comments on that line

Style/StderrPuts:
  Enabled: false # false alarms because not all $stderr.puts messages are Ruby style warnings

Style/PerlBackrefs:
  Enabled: false # sometimes there are no good alternatives

Style/IfUnlessModifier:
  Enabled: false # useful but sometimes the meaning is better conveyed using an if/unless statement

Style/InfiniteLoop:
  Enabled: false # why should Kernel#loop be better than while true?

Style/SpecialGlobalVars:
  Enabled: false # I think that $! and $? are recognizable in terms of their function

Style/MultipleComparison:
  Enabled: false # why should an array be created? especially if only two items are compared

Style/AccessModifierDeclarations:
  Enabled: false

Style/WhileUntilModifier:
  Enabled: false # I prefer to use either one or the other, depending on context

Style/FormatStringToken:
  Enabled: false # I don't care about this

Style/ExponentialNotation:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashEachMethods:
  Enabled: true
  Exclude:
    - lib/hexapdf/utils/object_hash.rb # hash may be changed during iteration
    - lib/hexapdf/font/true_type/subsetter.rb # hash is changed during iteration

Style/HashTransformValues:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: false

Layout/HashAlignment:
  EnforcedLastArgumentHashStyle: ignore_implicit

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Layout/TrailingWhitespace:
  Exclude:
    - test/hexapdf/test_parser.rb # bc xref
    - test/hexapdf/test_writer.rb # bc xref
    - test/hexapdf/test_revisions.rb # bc xref
    - test/hexapdf/test_document.rb # bc xref

Layout/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/EmptyLineAfterMagicComment:
  Enabled: false # we have the magic comment and then the license

Layout/AssignmentIndentation:
  Enabled: false # false alarms

Layout/SpaceAroundMethodCallOperator:
  Enabled: true


Naming/PredicateName:
  Exclude:
    - lib/hexapdf/font/true_type/table/post.rb

Naming/VariableNumber:
  Exclude:
    - lib/hexapdf/encryption/security_handler.rb # bc of n_plus_5

Naming/ConstantName:
  Exclude:
    - lib/hexapdf/dictionary_fields.rb

Naming/MemoizedInstanceVariableName:
  Exclude:
    - lib/hexapdf/font/encoding/glyph_list.rb

Naming/HeredocDelimiterNaming:
  Enabled: false # we like our delimiters short and obvious

Naming/MethodParameterName:
  Enabled: false # for points the names x,y are perfectly reasonable

Lint/LiteralAsCondition:
  Enabled: false # we use while true

Lint/SuppressedException:
  Exclude:
    - test/test_helper.rb

Lint/UselessAccessModifier:
  Exclude:
    - lib/hexapdf/dictionary_fields.rb # not useless

Lint/StructNewOverride:
  Enabled: true
  Exclude:
    - lib/hexapdf/font/true_type/table/directory.rb

Lint/RaiseException:
  Enabled: true

Lint/MissingSuper:
  Enabled: false # why the need to fallback to super?

Lint/ConstantDefinitionInBlock:
  Exclude:
    - test/**/*.rb

# These cops should be run manually from time to time
# Style/MutableConstant
# Style/RescueModifier
# Style/PerlBackrefs
# Style/IfUnlessModifier
