name: HexaPDF Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        ruby: ['2.6', '2.7', '3.0', '3.1', head]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: sudo apt install netpbm pngcheck
      if: matrix.os == 'ubuntu-latest'
    - run: bundle exec rake
      if: matrix.os == 'ubuntu-latest' && matrix.ruby == 'head'
    - run: bundle exec rake
      env:
        NO_SIMPLECOV: true
      if: matrix.os != 'ubuntu-latest' || matrix.ruby != 'head'
